[package]
name = "command-id"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
variant_count = "1.1"
cubeos-error = { git = "ssh://git@github.com/Cube-OS/cubeos-error.git"}